"""comp added

Revision ID: 273c0982b3d6
Revises: f5bedeae11bc
Create Date: 2023-07-30 14:03:32.581755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273c0982b3d6'
down_revision = 'f5bedeae11bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=64), nullable=True))

    with op.batch_alter_table('Vulnerability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vulnerability', schema=None) as batch_op:
        batch_op.drop_column('company_name')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
