"""role added added

Revision ID: 3ce8ecd2b29b
Revises: a207c33a2858
Create Date: 2023-07-29 22:44:03.167409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce8ecd2b29b'
down_revision = 'a207c33a2858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_User_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_User_role'))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
