"""init

Revision ID: 756e12937a8e
Revises: 
Create Date: 2023-12-30 01:24:17.328327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756e12937a8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vulnerability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve', sa.String(length=32), nullable=False),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Vulnerability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Vulnerability_cve'), ['cve'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Vulnerability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Vulnerability_cve'))

    op.drop_table('Vulnerability')
    # ### end Alembic commands ###
