"""vuln added

Revision ID: f5bedeae11bc
Revises: 3ce8ecd2b29b
Create Date: 2023-07-30 00:30:29.155780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5bedeae11bc'
down_revision = '3ce8ecd2b29b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vulnerability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve', sa.String(length=32), nullable=False),
    sa.Column('cvss', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('exploit_available', sa.String(length=10), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Vulnerability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Vulnerability_cve'), ['cve'], unique=True)
        batch_op.create_index(batch_op.f('ix_Vulnerability_name'), ['name'], unique=False)

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    with op.batch_alter_table('Vulnerability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Vulnerability_name'))
        batch_op.drop_index(batch_op.f('ix_Vulnerability_cve'))

    op.drop_table('Vulnerability')
    # ### end Alembic commands ###
